package main

import (
	"fmt"

	migratepkg "github.com/eblackrps/viaduct/internal/migrate"
	"github.com/spf13/cobra"
)

func newMigrateCommand() *cobra.Command {
	var planID string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "migrate",
		Short: "Execute a migration plan",
		Long:  "Execute a migration plan generated by Viaduct.",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := loadAppConfig(configPath)
			if err != nil {
				return fmt.Errorf("migrate: load config: %w", err)
			}
			catalog, err := openConnectorCatalog(cfg)
			if err != nil {
				return fmt.Errorf("migrate: %w", err)
			}
			defer catalog.Close()

			stateStore, err := openStateStore(cmd.Context(), cfg)
			if err != nil {
				return fmt.Errorf("migrate: open store: %w", err)
			}
			defer stateStore.Close()

			spec, err := migratepkg.ParseSpec(planID)
			if err != nil {
				return fmt.Errorf("migrate: %w", err)
			}
			spec.Options.DryRun = dryRun

			sourceConnector, targetConnector, err := connectorsForSpec(cfg, catalog, spec)
			if err != nil {
				return fmt.Errorf("migrate: %w", err)
			}

			orchestrator := migratepkg.NewOrchestrator(sourceConnector, targetConnector, stateStore, nil)
			state, err := orchestrator.Execute(cmd.Context(), spec)
			if err != nil {
				return fmt.Errorf("migrate: %w", err)
			}

			if output == "table" {
				fmt.Fprintf(cmd.OutOrStdout(), "Migration %s is in phase %s with %d workloads\n", state.ID, state.Phase, len(state.Workloads))
				return nil
			}

			return printStructuredOutput(output, state)
		},
	}

	cmd.Flags().StringVar(&planID, "plan", "", "Path to the migration spec")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Preview the migration without executing it")

	cobra.CheckErr(cmd.MarkFlagRequired("plan"))

	return cmd
}
