package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newMigrateCommand() *cobra.Command {
	var planID string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "migrate",
		Short: "Execute a migration plan",
		Long:  "Execute a migration plan generated by Viaduct.",
		RunE: func(cmd *cobra.Command, args []string) error {
			fmt.Fprintf(cmd.OutOrStdout(), "Migration not yet implemented for plan %s (dry-run=%t)\n", planID, dryRun)
			return nil
		},
	}

	cmd.Flags().StringVar(&planID, "plan", "", "Migration plan identifier")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Preview the migration without executing it")

	cobra.CheckErr(cmd.MarkFlagRequired("plan"))

	return cmd
}
