param(
    [string]$SourceBin = "bin/viaduct.exe",
    [string]$SourceWeb = "web",
    [string]$SourceConfigs = "configs",
    [string]$SourceExamples = "examples",
    [string]$SourceDocs = "docs",
    [string]$Prefix = "$env:LOCALAPPDATA\\Programs\\Viaduct"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $SourceBin)) {
    throw "viaduct install: binary not found at $SourceBin"
}

$binDir = Join-Path $Prefix "bin"
$shareDir = Join-Path $Prefix "share"
$viaductShareDir = Join-Path $shareDir "viaduct"
$webTarget = Join-Path $viaductShareDir "web"
$configTarget = Join-Path $viaductShareDir "configs"
$examplesTarget = Join-Path $viaductShareDir "examples"
$docsTarget = Join-Path $viaductShareDir "docs"
$etcDir = Join-Path $Prefix "etc\\viaduct"
$etcConfig = Join-Path $etcDir "config.yaml"

New-Item -ItemType Directory -Force -Path $binDir | Out-Null
New-Item -ItemType Directory -Force -Path $viaductShareDir | Out-Null
New-Item -ItemType Directory -Force -Path $etcDir | Out-Null

Copy-Item -LiteralPath $SourceBin -Destination (Join-Path $binDir "viaduct.exe") -Force

function Copy-Tree {
    param(
        [string]$SourcePath,
        [string]$TargetPath
    )

    if (-not (Test-Path -LiteralPath $SourcePath)) {
        return
    }

    if (Test-Path -LiteralPath $TargetPath) {
        Remove-Item -LiteralPath $TargetPath -Recurse -Force
    }
    Copy-Item -LiteralPath $SourcePath -Destination $TargetPath -Recurse -Force
}

Copy-Tree -SourcePath $SourceWeb -TargetPath $webTarget
Copy-Tree -SourcePath $SourceConfigs -TargetPath $configTarget
Copy-Tree -SourcePath $SourceExamples -TargetPath $examplesTarget
Copy-Tree -SourcePath $SourceDocs -TargetPath $docsTarget

if (-not (Test-Path -LiteralPath $etcConfig)) {
    $exampleConfig = Join-Path $SourceConfigs "config.example.yaml"
    if (Test-Path -LiteralPath (Join-Path $examplesTarget "lab\\kvm")) {
        $labAddress = (Join-Path $examplesTarget "lab\\kvm").Replace('\', '/')
        @"
# Generated by the Viaduct installer for the local lab workflow.
# Update this file when you move into a real environment.
insecure: false

sources:
  kvm:
    address: "$labAddress"
"@ | Set-Content -LiteralPath $etcConfig -NoNewline
    }
    elseif (Test-Path -LiteralPath $exampleConfig) {
        Copy-Item -LiteralPath $exampleConfig -Destination $etcConfig -Force
    }
}

Write-Host "Installed Viaduct to $Prefix"
Write-Host "  binary: $(Join-Path $binDir 'viaduct.exe')"
if (Test-Path -LiteralPath $webTarget) {
    Write-Host "  web assets: $webTarget"
}
if (Test-Path -LiteralPath $examplesTarget) {
    Write-Host "  examples: $examplesTarget"
}
if (Test-Path -LiteralPath $docsTarget) {
    Write-Host "  docs: $docsTarget"
}
if (Test-Path -LiteralPath $etcConfig) {
    Write-Host "  config: $etcConfig"
}
Write-Host ""
Write-Host "Next step:"
Write-Host "  $(Join-Path $binDir 'viaduct.exe') start --config `"$etcConfig`""
