#!/usr/bin/env sh
set -eu

PREFIX="${PREFIX:-/usr/local}"
SOURCE_BIN="${1:-bin/viaduct}"
SOURCE_WEB="${2:-web}"
SOURCE_CONFIGS="${3:-configs}"
SOURCE_EXAMPLES="${4:-examples}"
SOURCE_DOCS="${5:-docs}"
TARGET_BIN_DIR="${PREFIX}/bin"
TARGET_SHARE_DIR="${PREFIX}/share/viaduct"
TARGET_ETC_DIR="${PREFIX}/etc/viaduct"

if [ ! -f "${SOURCE_BIN}" ]; then
  echo "viaduct install: binary not found at ${SOURCE_BIN}" >&2
  exit 1
fi

copy_tree() {
  source_path="$1"
  target_path="$2"
  if [ ! -d "${source_path}" ]; then
    return 0
  fi

  rm -rf "${target_path}"
  mkdir -p "$(dirname "${target_path}")"
  cp -R "${source_path}" "${target_path}"
}

mkdir -p "${TARGET_BIN_DIR}" "${TARGET_SHARE_DIR}" "${TARGET_ETC_DIR}"
cp "${SOURCE_BIN}" "${TARGET_BIN_DIR}/viaduct"
chmod 0755 "${TARGET_BIN_DIR}/viaduct"

copy_tree "${SOURCE_WEB}" "${TARGET_SHARE_DIR}/web"
copy_tree "${SOURCE_CONFIGS}" "${TARGET_SHARE_DIR}/configs"
copy_tree "${SOURCE_EXAMPLES}" "${TARGET_SHARE_DIR}/examples"
copy_tree "${SOURCE_DOCS}" "${TARGET_SHARE_DIR}/docs"

if [ ! -f "${TARGET_ETC_DIR}/config.yaml" ]; then
  if [ -d "${TARGET_SHARE_DIR}/examples/lab/kvm" ]; then
    cat > "${TARGET_ETC_DIR}/config.yaml" <<EOF
# Generated by the Viaduct installer for the local lab workflow.
# Update this file when you move into a real environment.
insecure: false

sources:
  kvm:
    address: "${TARGET_SHARE_DIR}/examples/lab/kvm"
EOF
  elif [ -f "${SOURCE_CONFIGS}/config.example.yaml" ]; then
    cp "${SOURCE_CONFIGS}/config.example.yaml" "${TARGET_ETC_DIR}/config.yaml"
  fi
fi

echo "Installed Viaduct to ${PREFIX}"
echo "  binary: ${TARGET_BIN_DIR}/viaduct"
if [ -d "${TARGET_SHARE_DIR}/web" ]; then
  echo "  web assets: ${TARGET_SHARE_DIR}/web"
fi
if [ -d "${TARGET_SHARE_DIR}/examples" ]; then
  echo "  examples: ${TARGET_SHARE_DIR}/examples"
fi
if [ -d "${TARGET_SHARE_DIR}/docs" ]; then
  echo "  docs: ${TARGET_SHARE_DIR}/docs"
fi
if [ -f "${TARGET_ETC_DIR}/config.yaml" ]; then
  echo "  config: ${TARGET_ETC_DIR}/config.yaml"
fi
echo
echo "Next step:"
echo "  ${TARGET_BIN_DIR}/viaduct start --config ${TARGET_ETC_DIR}/config.yaml"
